-- insert 1 response in the first questionnaire

INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '1', '1', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '1', '2', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '1', '3', '3');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '1', '4', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '1', '5', '1');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '1', '6', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '1', '7', '2');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '1', '8', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '1', '9', '3');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '1', '10', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '1', '11', '3');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '1', '12', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '1', '13', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '1', '14', '2');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '1', '15', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '1', '16', '3');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '2', '17', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '2', '18', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '2', '19', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '2', '20', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '2', '21', '3');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '2', '22', '2');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '2', '23', '1');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '2', '24', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '2', '25', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '2', '26', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '2', '27', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '2', '28', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '3', '29', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '3', '30', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '3', '31', '3');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '3', '32', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '3', '33', '2');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '3', '34', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '3', '35', '3');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '3', '36', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '3', '37', '1');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '3', '38', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '3', '39', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '3', '40', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '3', '41', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '3', '42', '4');

INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '4', '43', '21');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '4', '44','21');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '4', '45','22');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('1', '4', '46','22');
INSERT INTO answerdata (user_account, Section, question, User_answer) VALUES ('1', '4', '47','I dont have any suggestions');



-- insert 2 reponse at the 1 questionnaire

INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '1', '1', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '1', '2', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '1', '3', '3');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '1', '4', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '1', '5', '1');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '1', '6', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '1', '7', '2');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '1', '8', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '1', '9', '3');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '1', '10', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '1', '11', '3');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '1', '12', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '1', '13', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '1', '14', '2');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '1', '15', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '1', '16', '3');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '2', '17', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '2', '18', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '2', '19', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '2', '20', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '2', '21', '3');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '2', '22', '2');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '2', '23', '1');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '2', '24', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '2', '25', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '2', '26', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '2', '27', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '2', '28', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '3', '29', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '3', '30', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '3', '31', '3');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '3', '32', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '3', '33', '2');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '3', '34', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '3', '35', '3');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '3', '36', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '3', '37', '1');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '3', '38', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '3', '39', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '3', '40', '4');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '3', '41', '5');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '3', '42', '4');

INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '4', '43', '21');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '4', '44','21');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '4', '45','22');
INSERT INTO answerdata (user_account, Section, question, answer) VALUES ('2', '4', '46','22');
INSERT INTO answerdata (user_account, Section, question, User_answer) VALUES ('2', '4', '47','I dont have any suggestions');
